services:
  spltrader:
    build:
      context: .
      target: final
    volumes:
      - ./config.json:/usr/src/app/config.json
    networks:
      - spl-net

  splmongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - spl-net

networks:
  spl-net:
    driver: bridge